DROP TABLE IF EXISTS iam.refresh_tokens CASCADE;
DROP TABLE IF EXISTS iam.sessions CASCADE;
DROP TABLE IF EXISTS iam.devices CASCADE;
DROP TABLE IF EXISTS iam.user_roles CASCADE;
DROP TABLE IF EXISTS iam.role_permissions CASCADE;
DROP TABLE IF EXISTS iam.permissions CASCADE;
DROP TABLE IF EXISTS iam.roles CASCADE;
DROP TABLE IF EXISTS iam.mfa_backup_codes CASCADE;
DROP TABLE IF EXISTS iam.mfa_totp_credentials CASCADE;
DROP TABLE IF EXISTS iam.users CASCADE;

DROP SCHEMA IF EXISTS iam CASCADE;
